[project]
name = "supermemo-toolkit"
version = "0.1.27"
description = "SuperMemo 增强工具(CLI命令行)。包含图链整理、EPUB图书转换导入、Latex公式转图片、sm2anki、修补导出标题乱码、卡片朗读等。"
readme = "README.md"
keywords = ["supermemo", "cli-app", "tooltik"]
classifiers = [
    "Topic :: Utilities",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
]
authors = [{ name = "tingshu", email = "xinglan42w@outlook.com" }]
license = { text = "GPL-2.0-only" }
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chardet>=7.4.3",
    "click>=8.4.2",
    "ebooklib>=0.20",
    "edge-tts>=7.2.8",
    "filetype>=1.2.0",
    "matplotlib>=3.10.9",
    "miniaudio>=1.71",
    "numpy>=2.2.6",
    "pillow>=12.3.0",
    "pyperclip>=1.11.0",
    "pypinyin>=0.55.0",
    "pyquery>=2.0.1",
    "python-magic>=0.4.27; sys_platform != \"win32\"",
    "python-magic-bin>=0.4.14; sys_platform == \"win32\"",
    "pywinauto>=0.6.9",
    "requests>=2.34.2",
    "sounddevice>=0.5.5",
    "tqdm>=4.69.1",
    "yattag>=1.16.1",
]

[dependency-groups]
dev = []

[project.urls]
homepage = "https://github.com/Zacharia2/SuperMemo-Toolkit"
repository = "https://github.com/Zacharia2/SuperMemo-Toolkit"
documentation = "https://docs.qq.com/doc/DQnRpb0VNUEVvR3dl"

[project.scripts]
smtk = "supermemo_toolkit.smtk:main"

[tool.pdm.build]
excludes = ["docs/**"]

[[tool.pdm.source]]
name = "tencent"
url = "https://mirrors.aliyun.com/pypi/simple/"
verify_ssl = true

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
