object ImgScaler: TImgScaler
  Left = 0
  Top = 0
  Caption = 'Image Scaling'
  ClientHeight = 275
  ClientWidth = 549
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnActivate = FormActivate
  OnCreate = FormCreate
  OnDeactivate = FormDeactivate
  PixelsPerInch = 96
  TextHeight = 13
  object CompressorImage: TImage
    Left = 367
    Top = 245
    Width = 25
    Height = 25
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Proportional = True
    Visible = False
  end
  object Scale: TLabel
    Left = 416
    Top = 12
    Width = 25
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = '&Scale'
    FocusControl = ScaleBar
  end
  object Size: TLabel
    Left = 416
    Top = 77
    Width = 19
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = 'Size'
  end
  object ScaledImage: TImage
    Left = 392
    Top = 245
    Width = 25
    Height = 25
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
  end
  object Quality: TLabel
    Left = 416
    Top = 44
    Width = 34
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = 'Quality'
  end
  object Label1: TLabel
    Left = 416
    Top = 111
    Width = 19
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = '&Left'
    FocusControl = LeftBar
  end
  object Label2: TLabel
    Left = 416
    Top = 142
    Width = 25
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = '&Right'
    FocusControl = RightBar
  end
  object Label3: TLabel
    Left = 416
    Top = 176
    Width = 18
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = '&Top'
    FocusControl = TopBar
  end
  object Label4: TLabel
    Left = 416
    Top = 208
    Width = 34
    Height = 13
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = '&Bottom'
    FocusControl = BottomBar
  end
  object ScaleBar: TTrackBar
    Left = 12
    Top = 12
    Width = 383
    Height = 16
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    LineSize = 3
    Max = 100
    Min = 3
    PageSize = 7
    Frequency = 5
    Position = 90
    TabOrder = 0
    OnChange = ScaleBarChange
  end
  object QualityBar: TTrackBar
    Left = 12
    Top = 44
    Width = 383
    Height = 16
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Max = 100
    Min = 5
    Frequency = 5
    Position = 80
    TabOrder = 1
    OnChange = ScaleBarChange
  end
  object SizeBar: TTrackBar
    Left = 12
    Top = 77
    Width = 383
    Height = 16
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Enabled = False
    Max = 100
    Position = 100
    TabOrder = 2
  end
  object Original: TButton
    Left = 128
    Top = 251
    Width = 105
    Height = 19
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Caption = 'Original'
    TabOrder = 8
    OnClick = OriginalClick
  end
  object OK: TBitBtn
    Left = 18
    Top = 251
    Width = 99
    Height = 19
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Kind = bkOK
    NumGlyphs = 2
    TabOrder = 7
    OnClick = OKClick
  end
  object Cancel: TBitBtn
    Left = 245
    Top = 251
    Width = 104
    Height = 19
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Kind = bkCancel
    NumGlyphs = 2
    TabOrder = 9
  end
  object LeftBar: TTrackBar
    Left = 12
    Top = 111
    Width = 383
    Height = 14
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Max = 100
    TabOrder = 3
    OnChange = ScaleBarChange
  end
  object RightBar: TTrackBar
    Left = 12
    Top = 142
    Width = 383
    Height = 16
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Max = 100
    Min = 5
    Position = 100
    TabOrder = 4
    OnChange = ScaleBarChange
  end
  object TopBar: TTrackBar
    Left = 12
    Top = 176
    Width = 383
    Height = 14
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Max = 100
    Position = 100
    TabOrder = 5
    OnChange = ScaleBarChange
  end
  object BottomBar: TTrackBar
    Left = 12
    Top = 208
    Width = 383
    Height = 15
    Margins.Left = 2
    Margins.Top = 2
    Margins.Right = 2
    Margins.Bottom = 2
    Max = 100
    Min = 5
    Position = 100
    TabOrder = 6
    OnChange = ScaleBarChange
  end
end
