name: Build Windows Executable

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v7.0.1

            - name: astral-sh/setup-uv
              uses: astral-sh/setup-uv@v10.0.1
              with:
                  version: "latest"

            - name: Install Python and dependencies
              run: |
                  uv python install 3.10
                  uv sync --frozen

            - name: Build Wheel
              run: uv build --wheel

            - name: Build Executable
              run: uv run pyinstaller smtk.spec

            - name: Upload to Release
              uses: softprops/action-gh-release@v3.0.2
              with:
                  files: |
                      dist/*.exe
                      dist/*.whl
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
